spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssafy_home?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
  mail:
    host: smtp.example.com
    port: 587
    username: your-smtp-username
    password: your-smtp-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  ai:
    openai:
      api-key: your-gms-key

jwt:
  secret: your-jwt-secret-key

molit:
  service-key: your-data-go-kr-service-key

vworld:
  api-key: your-vworld-api-key
