spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssafy_home?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
  ai:
    openai:
      api-key: your-openai-api-key

jwt:
  secret: your-jwt-secret-key

molit:
  service-key: your-data-go-kr-service-key

vworld:
  api-key: your-vworld-api-key
