DROP TABLE IF EXISTS batch_collection_log;
DROP TABLE IF EXISTS house_deal;
DROP TABLE IF EXISTS house;
DROP TABLE IF EXISTS region_code;

CREATE TABLE region_code (
    region_code VARCHAR(10) PRIMARY KEY,
    sido_name VARCHAR(20) NOT NULL,
    sigungu_name VARCHAR(30),
    dong_name VARCHAR(30),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE house (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code VARCHAR(10) NOT NULL,
    apt_name VARCHAR(100) NOT NULL,
    jibun VARCHAR(50) NOT NULL,
    road_address VARCHAR(100),
    build_year INT,
    house_type VARCHAR(10) NOT NULL,
    latitude DECIMAL(10, 7),
    longitude DECIMAL(10, 7),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_house_identity UNIQUE (region_code, apt_name, jibun, house_type),
    CONSTRAINT fk_house_region FOREIGN KEY (region_code) REFERENCES region_code(region_code)
);

CREATE TABLE house_deal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id BIGINT NOT NULL,
    deal_type VARCHAR(20) NOT NULL,
    deal_amount INT,
    deposit_amount INT,
    monthly_rent INT NOT NULL DEFAULT 0,
    deal_date DATE NOT NULL,
    area DECIMAL(6, 2) NOT NULL,
    floor INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_house_deal_identity
        UNIQUE (house_id, deal_type, deal_date, area, floor, deal_amount),
    CONSTRAINT fk_deal_house FOREIGN KEY (house_id) REFERENCES house(id)
);

CREATE TABLE batch_collection_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_execution_id BIGINT NOT NULL,
    job_name VARCHAR(100) NOT NULL,
    data_type VARCHAR(30) NOT NULL,
    region_code VARCHAR(10),
    year_month VARCHAR(6),
    house_type VARCHAR(20),
    deal_type VARCHAR(20),
    collected_count INT NOT NULL DEFAULT 0,
    skipped_count INT NOT NULL DEFAULT 0,
    failed_count INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP,
    ended_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
