spring:
  application:
    name: ssafy-home-backend
  config:
    import: classpath:secret/application-secret.yml
  sql:
    init:
      mode: always
      encoding: UTF-8
      continue-on-error: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.ssafy.home
  configuration:
    map-underscore-to-camel-case: true

server:
  servlet:
    session:
      timeout: 30m
