server:
  port: 8083

spring:
  application:
    name: ssafy-home-ai-service
  config:
    import:
      - optional:classpath:secret/application-secret.yml
      - optional:file:../secret/application-secret.yml
  ai:
    openai:
      base-url: https://gms.ssafy.io/gmsapi/api.openai.com
      chat:
        options:
          model: gpt-5.4-mini
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        collection-name: ssafy-home-docs
        initialize-schema: true
        tenant: SpringAiTenant
        database: SpringAiDatabase
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  access-token-expiration-millis: 3600000

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: when-authorized
